### ISSUE TITLE
Unable to install on Mac

### ISSUE THREAD

**Issue by shrasool** [mhausenblas/eksphemeral#6] opened 2019-08-09 15:28 UTC
Encountered multiple errors:
- export email address was optional in docs but it broke the installation script.
Fixed by exporting email address
- after that, I got an error during installation script about sam command.
Fixed by installing sam (also needed to upgrade xcode). Might be helpful to add it as a prerequisite in dependencies.
## breaking error
- current error is I think the CFN is unable to create the S3 bucket and upload. output below:

```
▶ curl -sL http://get.eksphemeral.info/install.sh | sudo --preserve-env bash
Cloning into '/Users/me/eksp'...
remote: Enumerating objects: 334, done.
remote: Counting objects: 100% (334/334), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 1688 (delta 153), reused 274 (delta 100), pack-reused 1354
Receiving objects: 100% (1688/1688), 5.53 MiB | 5.27 MiB/s, done.
Resolving deltas: 100% (1001/1001), done.
Attempting to download https://github.com/mhausenblas/eksphemeral/releases/download/v0.4.0/eksp-macos
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   601    0   601    0     0   1914      0 --:--:-- --:--:-- --:--:--  1920
100 2754k  100 2754k    0     0  1500k      0  0:00:01  0:00:01 --:--:-- 1957k
Trying to install EKSphemeral ...
Installing the EKSphemeral control plane, this might take a few minutes
Using S3 bucket eks-svc for the control plane service code
Using S3 bucket eks-cluster-meta to store cluster specifications
mkdir -p bin
curl -sL https://github.com/mhausenblas/eksphemeral/releases/download/v0.4.0/createcluster -o bin/createcluster
curl -sL https://github.com/mhausenblas/eksphemeral/releases/download/v0.4.0/destroycluster -o bin/destroycluster
curl -sL https://github.com/mhausenblas/eksphemeral/releases/download/v0.4.0/prolongcluster -o bin/prolongcluster
curl -sL https://github.com/mhausenblas/eksphemeral/releases/download/v0.4.0/status -o bin/status
chmod +x bin/*
sam package --template-file template.yaml --output-template-file eksp-stack.yaml --s3-bucket eks-svc

Unable to upload artifact bin/ referenced by CodeUri parameter of StatusFunc resource.
An error occurred (AllAccessDisabled) when calling the CreateMultipartUpload operation: All access to this object has been disabled
make: *** [up] Error 255
Something bad happened after command completed:: exit status 2
```

Mac OS version: 10.14.5
aws cli version: 1.15.76
sam version: 0.19.0

**Comment by mhausenblas** [comment] 2019-08-09 16:22
Thanks for reporting this @shrasool and inline, point for point, the comments:

> export email address was optional in docs but it broke the installation script.

That shouldn't happen, let me see if I can re-produce this.

> Fixed by installing sam (also needed to upgrade xcode). Might be helpful to add it as a prerequisite in dependencies.

Indeed, great catch! I have it listed in https://eksphemeral.info/dev/ but my bad, I forgot to add it to the main install instructions, will fix, ASAP! 

> current error is I think the CFN is unable to create the S3 bucket and upload

Maybe the instructions are not clear but you need to pick names for your buckets yourself, you re-used my bucket names there. That won't work, since you don't have write-access to my buckets.

**Comment by shrasool** [comment] 2019-08-09 16:38
My terminal buffer doesn't have that email error unfortunately so that's that.

My bad about naming, should have seen the "for example" written. It is still failing even though I can create the bucket using aws cli. Here is the new error now:
```
sam package --template-file template.yaml --output-template-file eksp-stack.yaml --s3-bucket eks-ice

Unable to upload artifact bin/ referenced by CodeUri parameter of StatusFunc resource.
S3 Bucket does not exist. Execute the command to create a new bucket
aws s3 mb s3://eks-ice
make: *** [up] Error 255
Something bad happened after command completed:: exit status 2
 
▶ aws s3 mb s3://eks-ice
make_bucket: eks-ice

▶ aws s3 ls                                                                 
2019-08-09 17:32:59 eks-ice
```

**Comment by mhausenblas** [comment] 2019-08-09 17:18
Hmm, it's a little hard to see what's going on but I'd suggest not to manually create the buckets but only set the env variables. Could be some location constraint missing.

**Comment by shrasool** [comment] 2019-08-09 18:27
The manual command at the end was just to confirm that the aws cli can create the buckets itself. Here is another run with different bucket name:

```
▶ curl -sL http://get.eksphemeral.info/install.sh | sudo --preserve-env bash
Cloning into '/Users/syedhamid/eksp'...
remote: Enumerating objects: 334, done.
remote: Counting objects: 100% (334/334), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 1688 (delta 153), reused 274 (delta 100), pack-reused 1354
Receiving objects: 100% (1688/1688), 5.53 MiB | 6.00 MiB/s, done.
Resolving deltas: 100% (1001/1001), done.
Attempting to download https://github.com/mhausenblas/eksphemeral/releases/download/v0.4.0/eksp-macos
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   601    0   601    0     0   1526      0 --:--:-- --:--:-- --:--:--  1529
100 2754k  100 2754k    0     0  1473k      0  0:00:01  0:00:01 --:--:-- 3064k
Trying to install EKSphemeral ...
Installing the EKSphemeral control plane, this might take a few minutes
Using S3 bucket eks-ice-2 for the control plane service code
Using S3 bucket eks-ice-2-cluster-meta to store cluster specifications
mkdir -p bin
curl -sL https://github.com/mhausenblas/eksphemeral/releases/download/v0.4.0/createcluster -o bin/createcluster
curl -sL https://github.com/mhausenblas/eksphemeral/releases/download/v0.4.0/destroycluster -o bin/destroycluster
curl -sL https://github.com/mhausenblas/eksphemeral/releases/download/v0.4.0/prolongcluster -o bin/prolongcluster
curl -sL https://github.com/mhausenblas/eksphemeral/releases/download/v0.4.0/status -o bin/status
chmod +x bin/*
sam package --template-file template.yaml --output-template-file eksp-stack.yaml --s3-bucket eks-ice-2

Unable to upload artifact bin/ referenced by CodeUri parameter of StatusFunc resource.
S3 Bucket does not exist. Execute the command to create a new bucket
aws s3 mb s3://eks-ice-2
make: *** [up] Error 255
Something bad happened after command completed:: exit status 2
```

**Comment by mhausenblas** [comment] 2019-08-10 08:07
Strange. I'll try to reproduce it.

**Comment by tomellis** [comment] 2019-08-20 15:15
Also hitting this but on Linux. It appears to be the S3 bucket not getting created from eksp-up.sh.
Running this manually... it does not create the bucket:
`
if [[ $(aws s3 ls | grep $EKSPHEMERAL_SVC_BUCKET) -ne 0 ]]; then
    aws s3api create-bucket \
        --bucket $EKSPHEMERAL_SVC_BUCKET \
        --create-bucket-configuration LocationConstraint=$(aws configure get region) \
        --region $(aws configure get region)
    echo "Created S3 bucket $EKSPHEMERAL_SVC_BUCKET"
fi
`
Taking the code out in isolation without the if loop, it does create the bucket, maybe timing and/or return code not being correct.

**Comment by mhausenblas** [comment] 2019-08-20 17:04
Cool, thanks @tomellis! I'm back from PTO tomorrow and will have a look.

**Comment by mhausenblas** [comment] 2019-08-26 17:52
OK, sorry for the delay. I _think_ I've fixed it with e91179d, can you please give it a try @tomellis and @shrasool?

**Comment by tomellis** [comment] 2019-08-28 15:33
Looks good to me @mhausenblas Thanks!

**Comment by mhausenblas** [comment] 2019-08-28 15:35
Thank you! I'll close it for now, and if @shrasool runs into problems with it, we can re-open it.

**Closed as completed by mhausenblas** 2019-08-28 15:35 UTC
Labels: bug
